// The demo command was automatically generated by Shenzhen Go.
package main

import (
	"sync"

	"fmt"
)

func Code(out chan<- int) {

	func(instanceNumber, multiplicity int) {

	}(0, 1)

}

func Node_2(bar <-chan rune, baz chan<- float64, foo <-chan int, quux chan<- string, qux chan<- int, tuz <-chan int64) {

	func(instanceNumber, multiplicity int) {
		fmt.Println("Node 2: Started.")
		fmt.Println("Node 2: Waiting on foo...")
		fmt.Printf("Node 2: Got %d on foo\n", <-foo)
		fmt.Println("Node 2: Finished.")
	}(0, 1)

}

func main() {

	channel1 := make(chan int, 0)

	var wg sync.WaitGroup

	wg.Add(1)
	go func() {
		Code(channel1)
		wg.Done()
	}()

	wg.Add(1)
	go func() {
		Node_2(nil, nil, channel1, nil, nil, nil)
		wg.Done()
	}()

	// Wait for the end
	wg.Wait()
}
