// The keycount command was automatically generated by Shenzhen Go.
package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"sync"
)

func Count_words(input <-chan string, output chan<- string, result chan<- map[string]uint) {
	const multiplicity = 1
	m := make(map[string]uint)
	const instanceNumber = 0
	for in := range input {
		m[in]++
		output <- in
	}
	result <- m
	close(output)
	close(result)
}

func Get_words(words chan<- string) {
	const multiplicity = 1

	const instanceNumber = 0
	fmt.Println("Enter a line of text:")
	s, err := bufio.NewReader(os.Stdin).ReadString('\n')
	if err != nil {
		panic(err)
	}
	for _, word := range strings.Fields(s) {
		words <- word
	}
	close(words)

}

func Print_summary(result <-chan map[string]uint) {
	const multiplicity = 1

	const instanceNumber = 0
	fmt.Printf("Got results: %v\n", <-result)

}

func Sink(input <-chan string) {
	const multiplicity = 1

	const instanceNumber = 0
	for range input {
	}

}

func main() {

	channel0 := make(chan string, 0)
	channel1 := make(chan string, 0)
	channel2 := make(chan map[string]uint, 0)

	var wg sync.WaitGroup

	wg.Add(1)
	go func() {
		Count_words(channel1, channel0, channel2)
		wg.Done()
	}()

	wg.Add(1)
	go func() {
		Get_words(channel1)
		wg.Done()
	}()

	wg.Add(1)
	go func() {
		Print_summary(channel2)
		wg.Done()
	}()

	wg.Add(1)
	go func() {
		Sink(channel0)
		wg.Done()
	}()

	// Wait for the end
	wg.Wait()
}
