#!/bin/bash
set -e
go build github.com/google/shenzhen-go/...
go test github.com/google/shenzhen-go/dev/client/view \
  github.com/google/shenzhen-go/dev/model \
  github.com/google/shenzhen-go/dev/server \
  github.com/google/shenzhen-go/dev/server/view \
  github.com/google/shenzhen-go/dev/source 
exit 0