// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shenzhen-go.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	shenzhen-go.proto

It has these top-level messages:
	Empty
	NodePin
	ChannelConfig
	NodeConfig
	SaveRequest
	SetChannelRequest
	SetGraphPropertiesRequest
	SetNodeRequest
	SetPositionRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NodePin struct {
	Node string `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Pin  string `protobuf:"bytes,2,opt,name=pin" json:"pin,omitempty"`
}

func (m *NodePin) Reset()                    { *m = NodePin{} }
func (m *NodePin) String() string            { return proto1.CompactTextString(m) }
func (*NodePin) ProtoMessage()               {}
func (*NodePin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodePin) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *NodePin) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type ChannelConfig struct {
	Name string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type string     `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Anon bool       `protobuf:"varint,3,opt,name=anon" json:"anon,omitempty"`
	Cap  uint64     `protobuf:"varint,4,opt,name=cap" json:"cap,omitempty"`
	Pins []*NodePin `protobuf:"bytes,5,rep,name=pins" json:"pins,omitempty"`
}

func (m *ChannelConfig) Reset()                    { *m = ChannelConfig{} }
func (m *ChannelConfig) String() string            { return proto1.CompactTextString(m) }
func (*ChannelConfig) ProtoMessage()               {}
func (*ChannelConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChannelConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChannelConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ChannelConfig) GetAnon() bool {
	if m != nil {
		return m.Anon
	}
	return false
}

func (m *ChannelConfig) GetCap() uint64 {
	if m != nil {
		return m.Cap
	}
	return 0
}

func (m *ChannelConfig) GetPins() []*NodePin {
	if m != nil {
		return m.Pins
	}
	return nil
}

type NodeConfig struct {
	Name         string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Enabled      bool    `protobuf:"varint,2,opt,name=enabled" json:"enabled,omitempty"`
	Multiplicity uint32  `protobuf:"varint,3,opt,name=multiplicity" json:"multiplicity,omitempty"`
	Wait         bool    `protobuf:"varint,4,opt,name=wait" json:"wait,omitempty"`
	PartCfg      []byte  `protobuf:"bytes,5,opt,name=part_cfg,json=partCfg,proto3" json:"part_cfg,omitempty"`
	PartType     string  `protobuf:"bytes,6,opt,name=part_type,json=partType" json:"part_type,omitempty"`
	X            float64 `protobuf:"fixed64,7,opt,name=x" json:"x,omitempty"`
	Y            float64 `protobuf:"fixed64,8,opt,name=y" json:"y,omitempty"`
}

func (m *NodeConfig) Reset()                    { *m = NodeConfig{} }
func (m *NodeConfig) String() string            { return proto1.CompactTextString(m) }
func (*NodeConfig) ProtoMessage()               {}
func (*NodeConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NodeConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *NodeConfig) GetMultiplicity() uint32 {
	if m != nil {
		return m.Multiplicity
	}
	return 0
}

func (m *NodeConfig) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *NodeConfig) GetPartCfg() []byte {
	if m != nil {
		return m.PartCfg
	}
	return nil
}

func (m *NodeConfig) GetPartType() string {
	if m != nil {
		return m.PartType
	}
	return ""
}

func (m *NodeConfig) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *NodeConfig) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type SaveRequest struct {
	Graph string `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
}

func (m *SaveRequest) Reset()                    { *m = SaveRequest{} }
func (m *SaveRequest) String() string            { return proto1.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()               {}
func (*SaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SaveRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

type SetChannelRequest struct {
	Graph   string         `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Channel string         `protobuf:"bytes,2,opt,name=channel" json:"channel,omitempty"`
	Config  *ChannelConfig `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *SetChannelRequest) Reset()                    { *m = SetChannelRequest{} }
func (m *SetChannelRequest) String() string            { return proto1.CompactTextString(m) }
func (*SetChannelRequest) ProtoMessage()               {}
func (*SetChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SetChannelRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *SetChannelRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SetChannelRequest) GetConfig() *ChannelConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetGraphPropertiesRequest struct {
	Graph       string `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	PackagePath string `protobuf:"bytes,3,opt,name=package_path,json=packagePath" json:"package_path,omitempty"`
	IsCommand   bool   `protobuf:"varint,4,opt,name=is_command,json=isCommand" json:"is_command,omitempty"`
}

func (m *SetGraphPropertiesRequest) Reset()                    { *m = SetGraphPropertiesRequest{} }
func (m *SetGraphPropertiesRequest) String() string            { return proto1.CompactTextString(m) }
func (*SetGraphPropertiesRequest) ProtoMessage()               {}
func (*SetGraphPropertiesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetGraphPropertiesRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *SetGraphPropertiesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetGraphPropertiesRequest) GetPackagePath() string {
	if m != nil {
		return m.PackagePath
	}
	return ""
}

func (m *SetGraphPropertiesRequest) GetIsCommand() bool {
	if m != nil {
		return m.IsCommand
	}
	return false
}

type SetNodeRequest struct {
	Graph  string      `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Node   string      `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
	Config *NodeConfig `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *SetNodeRequest) Reset()                    { *m = SetNodeRequest{} }
func (m *SetNodeRequest) String() string            { return proto1.CompactTextString(m) }
func (*SetNodeRequest) ProtoMessage()               {}
func (*SetNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetNodeRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *SetNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *SetNodeRequest) GetConfig() *NodeConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetPositionRequest struct {
	Graph string  `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Node  string  `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
	X     float64 `protobuf:"fixed64,3,opt,name=x" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,4,opt,name=y" json:"y,omitempty"`
}

func (m *SetPositionRequest) Reset()                    { *m = SetPositionRequest{} }
func (m *SetPositionRequest) String() string            { return proto1.CompactTextString(m) }
func (*SetPositionRequest) ProtoMessage()               {}
func (*SetPositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SetPositionRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *SetPositionRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *SetPositionRequest) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SetPositionRequest) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*NodePin)(nil), "proto.NodePin")
	proto1.RegisterType((*ChannelConfig)(nil), "proto.ChannelConfig")
	proto1.RegisterType((*NodeConfig)(nil), "proto.NodeConfig")
	proto1.RegisterType((*SaveRequest)(nil), "proto.SaveRequest")
	proto1.RegisterType((*SetChannelRequest)(nil), "proto.SetChannelRequest")
	proto1.RegisterType((*SetGraphPropertiesRequest)(nil), "proto.SetGraphPropertiesRequest")
	proto1.RegisterType((*SetNodeRequest)(nil), "proto.SetNodeRequest")
	proto1.RegisterType((*SetPositionRequest)(nil), "proto.SetPositionRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ShenzhenGo service

type ShenzhenGoClient interface {
	// Save saves the graph to disk.
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*Empty, error)
	// SetNode either creates a new channel (name == "", config != nil)
	// changes existing channel data such as name and attached pins (name is found, config != nil),
	// or deletes a channel (name is found, config == nil).
	SetChannel(ctx context.Context, in *SetChannelRequest, opts ...grpc.CallOption) (*Empty, error)
	// SetGraphProperties changes metdata such as name and package path.
	SetGraphProperties(ctx context.Context, in *SetGraphPropertiesRequest, opts ...grpc.CallOption) (*Empty, error)
	// SetNode either creates a new node (name == "", config != nil)
	// changes existing node such as name and multiplicity (name is found, config != nil),
	// or deletes a node (name is found, config == nil).
	SetNode(ctx context.Context, in *SetNodeRequest, opts ...grpc.CallOption) (*Empty, error)
	// SetPosition changes the node position in the diagram.
	SetPosition(ctx context.Context, in *SetPositionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type shenzhenGoClient struct {
	cc *grpc.ClientConn
}

func NewShenzhenGoClient(cc *grpc.ClientConn) ShenzhenGoClient {
	return &shenzhenGoClient{cc}
}

func (c *shenzhenGoClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.ShenzhenGo/Save", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shenzhenGoClient) SetChannel(ctx context.Context, in *SetChannelRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.ShenzhenGo/SetChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shenzhenGoClient) SetGraphProperties(ctx context.Context, in *SetGraphPropertiesRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.ShenzhenGo/SetGraphProperties", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shenzhenGoClient) SetNode(ctx context.Context, in *SetNodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.ShenzhenGo/SetNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shenzhenGoClient) SetPosition(ctx context.Context, in *SetPositionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.ShenzhenGo/SetPosition", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShenzhenGo service

type ShenzhenGoServer interface {
	// Save saves the graph to disk.
	Save(context.Context, *SaveRequest) (*Empty, error)
	// SetNode either creates a new channel (name == "", config != nil)
	// changes existing channel data such as name and attached pins (name is found, config != nil),
	// or deletes a channel (name is found, config == nil).
	SetChannel(context.Context, *SetChannelRequest) (*Empty, error)
	// SetGraphProperties changes metdata such as name and package path.
	SetGraphProperties(context.Context, *SetGraphPropertiesRequest) (*Empty, error)
	// SetNode either creates a new node (name == "", config != nil)
	// changes existing node such as name and multiplicity (name is found, config != nil),
	// or deletes a node (name is found, config == nil).
	SetNode(context.Context, *SetNodeRequest) (*Empty, error)
	// SetPosition changes the node position in the diagram.
	SetPosition(context.Context, *SetPositionRequest) (*Empty, error)
}

func RegisterShenzhenGoServer(s *grpc.Server, srv ShenzhenGoServer) {
	s.RegisterService(&_ShenzhenGo_serviceDesc, srv)
}

func _ShenzhenGo_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShenzhenGoServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShenzhenGo/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShenzhenGoServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShenzhenGo_SetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShenzhenGoServer).SetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShenzhenGo/SetChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShenzhenGoServer).SetChannel(ctx, req.(*SetChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShenzhenGo_SetGraphProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGraphPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShenzhenGoServer).SetGraphProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShenzhenGo/SetGraphProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShenzhenGoServer).SetGraphProperties(ctx, req.(*SetGraphPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShenzhenGo_SetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShenzhenGoServer).SetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShenzhenGo/SetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShenzhenGoServer).SetNode(ctx, req.(*SetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShenzhenGo_SetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShenzhenGoServer).SetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShenzhenGo/SetPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShenzhenGoServer).SetPosition(ctx, req.(*SetPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShenzhenGo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ShenzhenGo",
	HandlerType: (*ShenzhenGoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _ShenzhenGo_Save_Handler,
		},
		{
			MethodName: "SetChannel",
			Handler:    _ShenzhenGo_SetChannel_Handler,
		},
		{
			MethodName: "SetGraphProperties",
			Handler:    _ShenzhenGo_SetGraphProperties_Handler,
		},
		{
			MethodName: "SetNode",
			Handler:    _ShenzhenGo_SetNode_Handler,
		},
		{
			MethodName: "SetPosition",
			Handler:    _ShenzhenGo_SetPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shenzhen-go.proto",
}

func init() { proto1.RegisterFile("shenzhen-go.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xc5, 0x6d, 0xda, 0xb4, 0xd3, 0xee, 0x8a, 0x5a, 0x8b, 0x94, 0x82, 0x90, 0x42, 0xb8, 0x04,
	0x04, 0x0b, 0x2a, 0x12, 0xe2, 0x5e, 0xc1, 0xde, 0x50, 0xe5, 0x70, 0xe2, 0x52, 0x79, 0x53, 0x37,
	0xb1, 0x68, 0x6c, 0x6f, 0xe3, 0x85, 0x2d, 0x37, 0x4e, 0xfc, 0x08, 0xdf, 0xc2, 0x77, 0x21, 0x3b,
	0xae, 0x92, 0xa6, 0xa8, 0x88, 0x53, 0x66, 0x26, 0x7e, 0x9e, 0x79, 0xef, 0x8d, 0x61, 0x52, 0xe6,
	0x4c, 0x7c, 0xcf, 0x99, 0x78, 0x99, 0xc9, 0x4b, 0xb5, 0x95, 0x5a, 0xe2, 0x9e, 0xfd, 0x44, 0x3e,
	0xf4, 0xde, 0x17, 0x4a, 0xef, 0xa2, 0x57, 0xe0, 0x7f, 0x94, 0x2b, 0xb6, 0xe0, 0x02, 0x63, 0xf0,
	0x84, 0x5c, 0xb1, 0x00, 0x85, 0x28, 0x1e, 0x12, 0x1b, 0xe3, 0xfb, 0xd0, 0x55, 0x5c, 0x04, 0x1d,
	0x5b, 0x32, 0x61, 0xf4, 0x03, 0xc1, 0xd9, 0x3c, 0xa7, 0x42, 0xb0, 0xcd, 0x5c, 0x8a, 0x35, 0xcf,
	0x2c, 0x8e, 0x16, 0x35, 0x8e, 0x16, 0xcc, 0xd4, 0xf4, 0x4e, 0x31, 0x07, 0xb4, 0xb1, 0xa9, 0x51,
	0x21, 0x45, 0xd0, 0x0d, 0x51, 0x3c, 0x20, 0x36, 0x36, 0xf7, 0xa7, 0x54, 0x05, 0x5e, 0x88, 0x62,
	0x8f, 0x98, 0x10, 0x47, 0xe0, 0x29, 0x2e, 0xca, 0xa0, 0x17, 0x76, 0xe3, 0xd1, 0xec, 0xbc, 0x1a,
	0xfb, 0xd2, 0xcd, 0x48, 0xec, 0xbf, 0xe8, 0x37, 0x02, 0x30, 0x95, 0x13, 0x03, 0x04, 0xe0, 0x33,
	0x41, 0xaf, 0x37, 0x6c, 0x65, 0x67, 0x18, 0x90, 0x7d, 0x8a, 0x23, 0x18, 0x17, 0xb7, 0x1b, 0xcd,
	0xd5, 0x86, 0xa7, 0x5c, 0xef, 0xec, 0x38, 0x67, 0xe4, 0xa0, 0x66, 0x6e, 0xfc, 0x46, 0xb9, 0xb6,
	0x73, 0x0d, 0x88, 0x8d, 0xf1, 0x14, 0x06, 0x8a, 0x6e, 0xf5, 0x32, 0x5d, 0x67, 0x41, 0x2f, 0x44,
	0xf1, 0x98, 0xf8, 0x26, 0x9f, 0xaf, 0x33, 0xfc, 0x08, 0x86, 0xf6, 0x97, 0xa5, 0xdc, 0xb7, 0x53,
	0xd8, 0xb3, 0x9f, 0x0c, 0xed, 0x31, 0xa0, 0xbb, 0xc0, 0x0f, 0x51, 0x8c, 0x08, 0xba, 0x33, 0xd9,
	0x2e, 0x18, 0x54, 0xd9, 0x2e, 0x7a, 0x0a, 0xa3, 0x84, 0x7e, 0x65, 0x84, 0xdd, 0xdc, 0xb2, 0x52,
	0xe3, 0x0b, 0xe8, 0x65, 0x5b, 0xaa, 0x72, 0xc7, 0xa4, 0x4a, 0xa2, 0x1b, 0x98, 0x24, 0x4c, 0x3b,
	0xcd, 0x4f, 0x1e, 0x35, 0xac, 0xd3, 0xea, 0x9c, 0x53, 0x7e, 0x9f, 0xe2, 0x17, 0xd0, 0x4f, 0xad,
	0x5a, 0x96, 0xef, 0x68, 0x76, 0xe1, 0x84, 0x3d, 0xb0, 0x92, 0xb8, 0x33, 0xd1, 0x4f, 0x04, 0xd3,
	0x84, 0xe9, 0x2b, 0x73, 0xe9, 0x62, 0x2b, 0x15, 0xdb, 0x6a, 0xce, 0xca, 0xd3, 0xbd, 0xf7, 0x2e,
	0x74, 0x1a, 0x2e, 0x3c, 0x81, 0xb1, 0xa2, 0xe9, 0x17, 0x9a, 0xb1, 0xa5, 0xa2, 0x3a, 0xb7, 0xbd,
	0x87, 0x64, 0xe4, 0x6a, 0x0b, 0xaa, 0x73, 0xfc, 0x18, 0x80, 0x97, 0xcb, 0x54, 0x16, 0x05, 0x15,
	0x2b, 0x27, 0xf8, 0x90, 0x97, 0xf3, 0xaa, 0x10, 0x31, 0x38, 0x4f, 0x98, 0x36, 0x66, 0xff, 0xbb,
	0xbb, 0x59, 0xde, 0x4e, 0x63, 0x79, 0x9f, 0xb5, 0x38, 0x4f, 0x1a, 0xcb, 0xd4, 0x22, 0xfc, 0x19,
	0x70, 0xc2, 0xf4, 0x42, 0x96, 0x5c, 0x73, 0x29, 0xfe, 0xbf, 0x95, 0x35, 0xb9, 0x7b, 0x60, 0xb2,
	0xe7, 0x4c, 0x9e, 0xfd, 0xea, 0x00, 0x24, 0xee, 0x21, 0x5e, 0x49, 0xfc, 0x1c, 0x3c, 0xe3, 0x39,
	0xc6, 0x6e, 0x9a, 0xc6, 0x02, 0x3c, 0x1c, 0xbb, 0x5a, 0xf5, 0x36, 0xef, 0xe1, 0xb7, 0x00, 0xb5,
	0xf5, 0x38, 0xd8, 0x23, 0xda, 0xdb, 0x70, 0x84, 0xfb, 0x60, 0xe9, 0xb4, 0xec, 0xc3, 0x61, 0x8d,
	0xff, 0xbb, 0xb3, 0x47, 0xf7, 0xbc, 0x06, 0xdf, 0xa9, 0x8f, 0x1f, 0xd4, 0xe0, 0x86, 0x1b, 0x47,
	0x88, 0x77, 0x30, 0x6a, 0x08, 0x89, 0xa7, 0x35, 0xaa, 0x25, 0x6e, 0x1b, 0x79, 0xdd, 0xb7, 0xe9,
	0x9b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x78, 0x25, 0x90, 0xb5, 0x04, 0x00, 0x00,
}
