// The interrupt command was automatically generated by Shenzhen Go.
package main

import (
	"fmt"
	"os"
	"os/signal"
	"runtime"
	"sync"
)

var _ = runtime.Compiler

func Code() {
	// Code

	fmt.Println("Press Ctrl-C or send SIGINT to stop")
	it := make(chan os.Signal, 1)
	signal.Notify(it, os.Interrupt)
	<-it
	fmt.Println("Interrupted!")
}

func main() {

	var wg sync.WaitGroup

	wg.Add(1)
	go func() {
		Code()
		wg.Done()
	}()

	// Wait for the various goroutines to finish.
	wg.Wait()
}
