// The demo command was automatically generated by Shenzhen Go.
package main

import (
	"sync"
)

func blah() {

	func(instanceNumber, multiplicity int) {
		fmt.Println("blah")
	}(0, 1)

}

func main() {

	anonymous_channel_0 := make(chan int, 0)

	var wg sync.WaitGroup

	wg.Add(1)
	go func() {
		blah()
		wg.Done()
	}()

	// Wait for the end
	wg.Wait()
}
